import { Card } from "@/types";

export function getSampleCards(): Card[] {
  return [
    {
      id: "1",
      category: "안전관리",
      question: "산업안전보건법의 목적은?",
      answer: "1",
      choices: [
        "근로자의 안전과 보건을 보호하는 것",
        "사업주의 이익을 보호하는 것",
        "정부의 규제를 강화하는 것",
        "산업 발전을 촉진하는 것",
      ],
      explanation:
        "산업안전보건법 제1조에 따르면, 이 법은 근로자의 안전과 보건을 보호하고 쾌적한 작업환경을 조성함으로써 근로자의 생명과 신체를 보호하고, 나아가 산업재해를 예방하는 것을 목적으로 한다.",
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "2",
      category: "안전관리",
      question: "안전보건관리체계에서 최고경영자의 책임은?",
      answer: "2",
      choices: ["기술적 책임", "법적 책임", "경영적 책임", "도덕적 책임"],
      explanation:
        "최고경영자는 안전보건에 대한 최종 책임을 지며, 이는 법적으로 명시된 의무이다. 안전보건법상 사업주는 근로자의 안전과 보건을 보호할 법적 책임이 있다.",
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "3",
      category: "안전관리",
      question: "산업재해율을 계산하는 공식은?",
      answer: "1",
      choices: [
        "재해율 = (재해건수 / 연근로시간) × 1,000,000",
        "재해율 = (재해건수 / 근로자수) × 100",
        "재해율 = (재해건수 / 작업일수) × 1,000",
        "재해율 = (재해건수 / 총근로시간) × 100,000",
      ],
      explanation:
        "산업재해율은 연근로시간 100만 시간당 재해건수로 계산한다. 이는 국제적으로 통용되는 표준 지표로, 산업재해 발생 빈도를 정확히 측정하기 위한 공식이다.",
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "4",
      category: "안전관리",
      question: "안전보건교육은 입체 시 몇 시간 이상 실시해야 하는가?",
      answer: "3",
      choices: ["4시간", "6시간", "8시간", "10시간"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "5",
      category: "안전관리",
      question: "위험성 평가에서 위험도는 무엇으로 계산하는가?",
      answer: "1",
      choices: ["발생가능성 × 심각성", "발생빈도 × 손실규모", "위험도 × 노출도", "확률 × 영향도"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "6",
      category: "안전관리",
      question: "안전보건 목표의 SMART 원칙에서 S는 무엇을 의미하는가?",
      answer: "1",
      choices: ["Specific (구체적)", "Simple (단순한)", "Systematic (체계적)", "Standard (표준)"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "7",
      category: "안전관리",
      question: "안전보건경영시스템의 핵심은?",
      answer: "4",
      choices: ["규제 준수", "비용 절감", "생산성 향상", "지속적 개선"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "8",
      category: "안전관리",
      question: "안전보건위원회의 구성원 수는?",
      answer: "3",
      choices: [
        "항상 동일하다",
        "산업별로 다르다",
        "사업장 규모에 따라 달라진다",
        "법으로 정해져 있다",
      ],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "9",
      category: "안전관리",
      question: "안전점검의 종류에는 일상점검, 정기점검 외에 무엇이 있는가?",
      answer: "2",
      choices: ["임시점검", "특별점검", "수시점검", "예방점검"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "10",
      category: "안전관리",
      question: "재해발생 시 4시간 이내에 보고해야 하는 기관은?",
      answer: "1",
      choices: ["고용노동부", "소방청", "경찰청", "보건복지부"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "11",
      category: "안전관리",
      question: "안전보건표지의 색상 중 경고를 나타내는 색은?",
      answer: "3",
      choices: ["빨간색", "파란색", "노란색", "초록색"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "12",
      category: "안전관리",
      question: "안전보건표지의 색상 중 금지를 나타내는 색은?",
      answer: "1",
      choices: ["빨간색", "파란색", "노란색", "초록색"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "13",
      category: "안전관리",
      question: "안전보건표지의 색상 중 안전을 나타내는 색은?",
      answer: "4",
      choices: ["빨간색", "파란색", "노란색", "초록색"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "14",
      category: "안전관리",
      question: "개인보호구 착용에 대한 설명으로 옳은 것은?",
      answer: "2",
      choices: ["선택사항이다", "필수사항이다", "작업 종류에 따라 다르다", "근로자 재량에 맡긴다"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "15",
      category: "안전관리",
      question: "안전모의 사용기한은 보통 몇 년인가?",
      answer: "2",
      choices: ["2년", "3년", "4년", "5년"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "16",
      category: "안전관리",
      question: "안전화의 주요 기능은?",
      answer: "1",
      choices: ["발가락 보호", "발목 보호", "미끄럼 방지", "충격 흡수"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "17",
      category: "안전관리",
      question: "작업 전 점검에 대한 설명으로 옳은 것은?",
      answer: "3",
      choices: ["불필요하다", "선택사항이다", "필수사항이다", "주기적으로만 실시한다"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "18",
      category: "안전관리",
      question: "작업 중단 조건에는 날씨, 장비 이상 외에 무엇이 있는가?",
      answer: "3",
      choices: ["시간 부족", "인원 부족", "인적 오류", "비용 초과"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "19",
      category: "안전관리",
      question: "작업허가제의 목적은?",
      answer: "1",
      choices: ["위험작업 관리", "작업 효율 향상", "비용 절감", "인력 배치"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "20",
      category: "안전관리",
      question: "안전보건교육은 연 몇 회 이상 실시해야 하는가?",
      answer: "1",
      choices: ["1회", "2회", "3회", "4회"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "21",
      category: "안전관리",
      question: "신규 채용 시 안전보건교육은 몇 시간 이상 실시해야 하는가?",
      answer: "3",
      choices: ["4시간", "6시간", "8시간", "10시간"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "22",
      category: "안전관리",
      question: "안전보건교육의 종류에는 일반교육 외에 무엇이 있는가?",
      answer: "2",
      choices: ["기본교육", "특별교육", "보수교육", "심화교육"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "23",
      category: "안전관리",
      question: "위험물 취급 작업에 대한 설명으로 옳은 것은?",
      answer: "1",
      choices: [
        "특별교육이 필요하다",
        "일반교육만 필요하다",
        "교육이 불필요하다",
        "선택적 교육이다",
      ],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "24",
      category: "안전관리",
      question: "작업환경 측정은 몇 개월마다 실시하는가?",
      answer: "2",
      choices: ["3개월", "6개월", "9개월", "12개월"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "25",
      category: "안전관리",
      question: "작업환경 측정의 목적은?",
      answer: "1",
      choices: ["유해인자 확인", "작업 효율 측정", "비용 절감", "인력 배치"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "26",
      category: "안전관리",
      question: "안전보건표지 설치에 대한 설명으로 옳은 것은?",
      answer: "2",
      choices: [
        "선택적으로 설치해도 된다",
        "필수적으로 설치해야 한다",
        "작업장 규모에 따라 다르다",
        "법으로 정해져 있지 않다",
      ],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "27",
      category: "안전관리",
      question: "비상구는 최소 몇 개 이상 설치해야 하는가?",
      answer: "2",
      choices: ["1개", "2개", "3개", "4개"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "28",
      category: "안전관리",
      question: "비상구의 너비는 최소 얼마인가?",
      answer: "3",
      choices: ["50cm", "60cm", "75cm", "90cm"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "29",
      category: "안전관리",
      question: "소화기의 점검은 몇 개월마다 실시해야 하는가?",
      answer: "1",
      choices: ["월 1회", "월 2회", "분기 1회", "반기 1회"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
    {
      id: "30",
      category: "안전관리",
      question: "소화기의 종류에는 분말소화기 외에 무엇이 있는가?",
      answer: "2",
      choices: ["가스소화기", "물소화기", "화학소화기", "전기소화기"],
      type: "multiple_choice",
      source: "샘플 데이터",
    },
  ];
}

export function isSupabaseConfigured(): boolean {
  return !!(
    process.env.NEXT_PUBLIC_SUPABASE_URL &&
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY &&
    process.env.NEXT_PUBLIC_SUPABASE_URL !== "your_supabase_url" &&
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY !== "your_supabase_anon_key"
  );
}
